# Generated by Django 5.1.5 on 2025-02-21 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistroUsuario',
        ),
    ]
