# Generated by Django 5.1.5 on 2025-02-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_muestra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla1_muestras', models.ManyToManyField(blank=True, related_name='tabla1', to='contacts.muestra')),
                ('tabla2_muestras', models.ManyToManyField(blank=True, related_name='tabla2', to='contacts.muestra')),
            ],
        ),
    ]
