# Generated by Django 5.1.5 on 2025-03-03 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_tabla'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestra',
            name='orden_produccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muestras', to='contacts.ordenproduccion'),
        ),
        migrations.AddField(
            model_name='tabla',
            name='orden_produccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tablas', to='contacts.ordenproduccion'),
        ),
    ]
