# Generated by Django 5.1.5 on 2025-03-03 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_muestra_orden_produccion_tabla_orden_produccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestra',
            name='noordenproduccion',
            field=models.CharField(default='Valor predeterminado', max_length=100),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='orden_produccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.ordenproduccion'),
        ),
    ]
