# Generated by Django 5.1.5 on 2025-03-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_muestra_noordenproduccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muestra',
            name='noordenproduccion',
            field=models.CharField(default='NULL', max_length=100),
        ),
    ]
