# Generated by Django 5.1.5 on 2025-03-28 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_notificacion_alter_detalleorden_cantidad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
