# Generated by Django 5.1.5 on 2025-04-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='formatorecepcionmateriaprima',
            name='cantidadneto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='fechacaducidad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='fechainicioproceso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='fechaterminoproceso',
            field=models.DateField(blank=True, null=True),
        ),
    ]
