# Generated by Django 5.1.5 on 2025-02-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0034_registrousuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kardexrecepcionmateriaprimaalmacen',
            name='cantidadneto',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad Neto'),
        ),
        migrations.AlterField(
            model_name='kardexrecepcionmateriaprimaalmacen',
            name='cantidadqueda',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad Queda'),
        ),
        migrations.AlterField(
            model_name='kardexrecepcionmateriaprimaalmacen',
            name='cantidadsale',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad Sale'),
        ),
    ]
