# Generated by Django 5.1.5 on 2025-02-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0035_alter_kardexrecepcionmateriaprimaalmacen_cantidadneto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrousuario',
            name='tipousuario',
            field=models.CharField(choices=[('admin', 'Administrador'), ('admin2', 'Administrador2'), ('ent', 'Entrada'), ('alm', 'Almacen'), ('prod', 'Produccion'), ('cal', 'calidad')], max_length=100, verbose_name='Tipo Usuario'),
        ),
    ]
