# Generated by Django 5.1.5 on 2025-02-06 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0036_alter_registrousuario_tipousuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistroUsuario',
        ),
    ]
