# Generated by Django 5.1.5 on 2025-02-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0037_delete_registrousuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellidopaterno', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('apellidomaterno', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('tipousuario', models.CharField(choices=[('admin', 'Administrador'), ('admin2', 'Administrador2'), ('ent', 'Entrada'), ('alm', 'Almacen'), ('prod', 'Produccion'), ('cal', 'calidad')], max_length=100, verbose_name='Tipo Usuario')),
                ('correo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Correo')),
                ('contraseña', models.CharField(max_length=100, verbose_name='Contraseña')),
                ('confirmacioncontraseña', models.CharField(max_length=100, verbose_name='Confirmacion Contraseña')),
            ],
        ),
    ]
