# Generated by Django 5.1.5 on 2025-02-07 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0039_alter_kardexrecepcionmateriaprimaalmacen_cantidadneto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kardexrecepcionmateriaprimaalmacen',
            name='formato_recepcion',
        ),
    ]
