# Generated by Django 5.1.5 on 2025-02-07 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0040_remove_kardexrecepcionmateriaprimaalmacen_formato_recepcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='kardexrecepcionmateriaprimaalmacen',
            name='formato_recepcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.formatorecepcionmateriaprima'),
        ),
    ]
